version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: banco_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Alt!ora2015"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  backend:
    build: ./full-Stack-BP/full-Stack-BP 
    container_name: banco_backend
    environment:
      DB_HOST: sqlserver
    ports:
      - "8098:8098"
    depends_on:
      - sqlserver
    restart: unless-stopped

  frontend:
    build:
      context: ./full-stack-bp-frontend
      dockerfile: Dockerfile
    container_name: banco_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlserver_data: